### ISSUE TITLE
CanopyView doesn't render?

### ISSUE THREAD

**Issue by Tossrock** [SotSF/conjurer#9]
The CanopyView canvas is blank for me, tested in both Chrome and Firefox:

![image](https://user-images.githubusercontent.com/284311/231056837-a727780b-3812-43cf-b30e-70f8dffca192.png)

No errors in the console on either.

**Comment by brollin** [comment]
Fixed by https://github.com/SotSF/conjurer/commit/1a0130fe6055604a1a1297a55f8ff3ec5d810ab3 🥳

**Comment by Tossrock** [comment]
Curse you, [inconsistent platform specific WebGL implementations](https://stackoverflow.com/questions/66781512/why-doesnt-pointsize-default-to-a-standard-value-in-webgl)!!!!
